In [24]:
import warnings
warnings.filterwarnings('ignore')

In [25]:
import numpy as np
import pandas as pd
from pathlib import Path

In [26]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [49]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [82]:
# Load the data
file_path = Path('resources','LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

#to account for dropped columns/missing values
df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-19,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-19,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-19,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-19,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-19,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [51]:
# Create our features
X = df.drop(columns='loan_status')
X = X.loc[:, :].copy()
#make categories numerical
X = pd.get_dummies(X)

# Create our target
y = df.loc[:, target].copy()

In [52]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [53]:
X.columns

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'issue_d_Feb-2019', 'issue_d_Jan-2019', 'issue_d_Mar-2019',
       'pymnt_plan_n', 'initial_list_status_f', 'initial_list_status_w',
       'next_pymnt_d_Apr-2019', 'next_pymnt_d_May-2019',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'debt_settlement_flag_N'],
      dtype='object')

In [54]:
# Check the balance of our target values
y['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [73]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

# Create a random forest classifier
rf_model = BalancedRandomForestClassifier(n_estimators=100, random_state=2) 
# fit the model
rf_model.fit(X_train, y_train)
# make predictions using the testing data
predictions = rf_model.predict(X_test)
predictions

array(['low_risk', 'high_risk', 'low_risk', ..., 'low_risk', 'low_risk',
       'low_risk'], dtype=object)

In [74]:
# Calculated the balanced accuracy score
acc_score = balanced_accuracy_score(y_test, predictions)
acc_score

0.7958065509544405

In [75]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0           72           29
Actual 1         2074        15030

In [76]:
# Print the imbalanced classification report
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("------------------------------------")
print("Classification Report")
print(classification_report_imbalanced(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0           72           29
Actual 1         2074        15030

Accuracy Score : 0.7958065509544405
------------------------------------
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.71      0.88      0.06      0.79      0.62       101
   low_risk       1.00      0.88      0.71      0.93      0.79      0.64     17104

avg / total       0.99      0.88      0.71      0.93      0.79      0.64     17205

In [77]:
# List the features sorted in descending order by feature importance
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.0681665717531686, 'total_rec_prncp'),
 (0.06113107837426328, 'total_pymnt_inv'),
 (0.06103387202119355, 'total_rec_int'),
 (0.06054392343484646, 'last_pymnt_amnt'),
 (0.04985892027089026, 'total_pymnt'),
 (0.03518144362969146, 'int_rate'),
 (0.020595904424666387, 'issue_d_Jan-2019'),
 (0.018798204995319097, 'installment'),
 (0.01810365461349336, 'mths_since_recent_inq'),
 (0.017521553786864055, 'total_bc_limit'),
 (0.016825435814195412, 'out_prncp'),
 (0.016755484551157884, 'out_prncp_inv'),
 (0.015914530019987126, 'tot_hi_cred_lim'),
 (0.01588152996346426, 'max_bal_bc'),
 (0.015671010353816475, 'dti'),
 (0.015317881374959055, 'tot_cur_bal'),
 (0.015194393174504052, 'annual_inc'),
 (0.014698774121942312, 'bc_util'),
 (0.014688211442178517, 'avg_cur_bal'),
 (0.013833518621140102, 'mths_since_rcnt_il'),
 (0.01359833816374581, 'mo_sin_old_il_acct'),
 (0.013422925267309488, 'loan_amnt'),
 (0.013285725207562505, 'total_rev_hi_lim'),
 (0.013255195316064089, 'all_util'),
 (0.013163753572187777, 'total_bal_ex_mort'),
 (0.012681843530590032, 'mo_sin_old_rev_tl_op'),
 (0.012574999612561257, 'bc_open_to_buy'),
 (0.01254961212242622, 'total_il_high_credit_limit'),
 (0.012410879710818966, 'num_rev_accts'),
 (0.01215335511654749, 'total_bal_il'),
 (0.012138387345671572, 'il_util'),
 (0.011716960452802953, 'total_acc'),
 (0.011284921633510138, 'issue_d_Mar-2019'),
 (0.010843707472262046, 'num_bc_tl'),
 (0.010722796598338675, 'acc_open_past_24mths'),
 (0.010454226086640326, 'revol_bal'),
 (0.010256482145109942, 'num_il_tl'),
 (0.009842340139436316, 'mths_since_recent_bc'),
 (0.009824989514961496, 'pct_tl_nvr_dlq'),
 (0.009767107300285275, 'mo_sin_rcnt_rev_tl_op'),
 (0.009605042564121813, 'open_acc'),
 (0.009329460211358593, 'mo_sin_rcnt_tl'),
 (0.00926677149796021, 'num_tl_op_past_12m'),
 (0.008999055329549695, 'num_rev_tl_bal_gt_0'),
 (0.008850885425379746, 'num_sats'),
 (0.008720728327610313, 'num_op_rev_tl'),
 (0.00822085030063509, 'percent_bc_gt_75'),
 (0.008140658927077575, 'inq_last_12m'),
 (0.007683387552208048, 'num_actv_bc_tl'),
 (0.007480626053593805, 'inq_fi'),
 (0.006630345324662315, 'total_cu_tl'),
 (0.006438655460473691, 'open_il_24m'),
 (0.00637553278485064, 'open_act_il'),
 (0.0061830389746095355, 'num_actv_rev_tl'),
 (0.006152783949647496, 'open_acc_6m'),
 (0.006016700113951949, 'num_bc_sats'),
 (0.005437804797036862, 'inq_last_6mths'),
 (0.005349655082149388, 'open_rv_24m'),
 (0.005251055087151299, 'next_pymnt_d_Apr-2019'),
 (0.005238747525286866, 'total_rec_late_fee'),
 (0.0048075970544377185, 'open_rv_12m'),
 (0.004775226860329717, 'tot_coll_amt'),
 (0.004600004998348772, 'open_il_12m'),
 (0.004580468650364907, 'mort_acc'),
 (0.004425709254226102, 'delinq_2yrs'),
 (0.0035515994149818582, 'num_accts_ever_120_pd'),
 (0.0034002930167175635, 'next_pymnt_d_May-2019'),
 (0.0032530660586290307, 'issue_d_Feb-2019'),
 (0.002176683495620839, 'pub_rec_bankruptcies'),
 (0.0018634388115220724, 'verification_status_Source Verified'),
 (0.0017471899287374018, 'home_ownership_RENT'),
 (0.0017126246198215333, 'application_type_Joint App'),
 (0.001707409902235319, 'application_type_Individual'),
 (0.0016770930826665257, 'verification_status_Verified'),
 (0.0015176552482656434, 'pub_rec'),
 (0.0013577233963987297, 'verification_status_Not Verified'),
 (0.0013168209801027791, 'home_ownership_OWN'),
 (0.0010652934730675237, 'home_ownership_MORTGAGE'),
 (0.000961120311877491, 'initial_list_status_w'),
 (0.0009409489239546787, 'initial_list_status_f'),
 (0.000703609532580349, 'num_tl_90g_dpd_24m'),
 (0.00038768734184007583, 'collections_12_mths_ex_med'),
 (0.0002926702534146994, 'home_ownership_ANY'),
 (0.00014183704996981265, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [78]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier

ec_model = EasyEnsembleClassifier(n_estimators=100, random_state=2) 
# fit the model
ec_model.fit(X_train, y_train)
# make predictions using the testing data
predictions = ec_model.predict(X_test)
predictions

array(['low_risk', 'low_risk', 'low_risk', ..., 'low_risk', 'low_risk',
       'low_risk'], dtype=object)

In [79]:
# Calculated the balanced accuracy score
acc_score = balanced_accuracy_score(y_test, predictions)
acc_score

0.933852541007141

In [80]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0           93            8
Actual 1          908        16196

In [81]:
# Print the imbalanced classification report
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("------------------------------------")
print("Classification Report")
print(classification_report_imbalanced(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0           93            8
Actual 1          908        16196

Accuracy Score : 0.933852541007141
------------------------------------
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.09      0.92      0.95      0.17      0.93      0.87       101
   low_risk       1.00      0.95      0.92      0.97      0.93      0.87     17104

avg / total       0.99      0.95      0.92      0.97      0.93      0.87     17205